### ISSUE TITLE
How to get started, AppSensor + php or GO web application

### ISSUE THREAD

**Issue by tyyko** [jtmelton/appsensor#20]
Hello, It's been some days that I'm studying all the material I found, starting from the youtube videos to the official pdf guide.

Most of the material talks about the philosophy of the project, and how you can use it to monitor a lot of events, but nothing on how to really deploy it!

I'd like to try it on a helloworld php (and also on a GO)application. These application may be deployed on the cloud on multiple instances, so I think that the best deployment model would be with RabbitMQ(correct me if I am wrong).

What I should do to deploy appsensor to listen on RabbitMQ for inputs? 
And I assume there is a dashboard to monitor the situation.

How can I tell a php o GO app to write on RabbitMQ(not just write a message, but how the message should be, I only seen the java example of an event)

A step-by-step guide to deploy AppSensor on a dummy php app with a login form would be great and allow more people to start implementing this project! 

Thank you!
Michael

**Comment by jtmelton** [comment]
Michael, 

Good questions. I'll try to answer each in turn: 

- Yes, much of the documentation is related to concepts of what it is and why to use it, but there is less documentation of the how. We're trying to resolve that as we go, but there can always be more. There is a getting started guide at appsensor.org that you can go through that should help. In addition, there are readme's setup for several of the subprojects that need specific documentation. 

- As for PHP, Go, etc. the code only has reference clients in Java, but others should be straightforward to build. We've had folks do a C# version and a NodeJS client so far. The project will try to point to those non-official clients as people notify us.

- As for non-jvm deployment, you could use anything other than "local", which means you could do any of the following: [REST, SOAP, thrift, RabbitMQ, kafka]

- Since you asked about RabbitMQ directly, there is a good bit of javadoc here that should help for both the client and server: https://github.com/jtmelton/appsensor/blob/dev-v2.1/execution-modes/appsensor-amqp-rabbitmq-client/src/main/java/org/owasp/appsensor/amqp/rabbitmq/event/RabbitMqEventManager.java and https://github.com/jtmelton/appsensor/blob/dev-v2.1/execution-modes/appsensor-amqp-rabbitmq-server/src/main/java/org/owasp/appsensor/amqp/rabbitmq/RabbitMqRequestHandler.java

- There is currently no dashboard. That is likely the biggest problem right now. At the end of the month, there is a session to be held at appsec EU to design the reference dashboard. After that we'll begin building it. If you have ideas there, that session would be great to contribute to, either by giving input before or feedback after the event. 

- As for the event/attack data model, it is sent as JSON so any language can produce and consume it easily. That's generally true for the other modes as well (except thrift which has it's own format, with associated code generators)

- I'm currently building a couple of example apps right now. They are in Java, but should give an example for how to build a client without much effort. My hope is that we can build the reference java implementation and others will build support for other languages. The core of the system and majority of the code is the server-side portion. 

Hope this helps!

Thanks,
John

**Comment by tyyko** [comment]
First of all, Thank you for your answers!!

If you prefer me to ask the next questions using another way (forum, mailing list,..) just tell me!

So I imagine that videos like this https://www.youtube.com/watch?v=YZ5zGQ-XLkk are not part of appsensor but written as application code, that does query on appsensor database, right?


The following is not a 'complaint' to the project, just consideration from a student that did not understood completely what appsensor is :)

I'm still missing some fundamental stuff, like the architecture of the deployment: I see AppSensor as a server somewhere listening for events (on RabbitMQ in this case) and sending back to the application the action to take.
But if it's only this, and I have to implement the detection and response stuff on my application, and the project doesn't have (at this time) a dashboard/monitoring and reporting solution, what is the added value of deploy one of these for each application? It seems that if I'm interested only on detect attacks and take same actions, there is not so much difference on implementing all directly on the application, and write a little server to receive data and report the situation of all the instances, or even all the application I deployed.

My main goal is: I have some applications to deploy on the cloud, and I want to track and monitor performance and attacks (both successful and unsuccessful)

Thank you for your help!
Michael

**Comment by jtmelton** [comment]
Michael, 

I certainly don't take your comments as criticism - they are all valid points and things we are trying to address.

This is a fine place to discuss. The demo you pointed out on youtube was done by one of the project leaders (Colin Watson) and is not a real application - it's just a wireframe essentially to explain the concept and show a possible idea for what might be done. 

For short history of the project, there was a version 1 that was Java-only and essentially was a library that ran as part of the application, so we didn't have a UI. The version 2 codebase is a full re-write that makes it possible to use any language on the client and communicate over standard transports (rest, soap, thrift, rabbit, kafka, etc.) to communicate events/attacks/responses. 

For the architecture, yes, appsensor is mainly the "server" that we call the analysis engine (see the glossary in https://www.owasp.org/images/0/02/Owasp-appsensor-guide-v2.pdf for standard terms). The business applications you want to protect are called "client applications" in our terminology. Those applications (clients) send events to the appsensor analysis engine (server) and then poll for "responses" that they should take. 

You could easily build this on your own obviously (and others have), but the goal of the project is to build a standardized tool that everyone can use that will do that. That means a lot of integrations, which has been the focus so far, and then certainly a dashboard (our next big project that hasn't happened yet). 

To accomplish your goal (use case), you can certainly use appsensor, and the basic steps would be:
- Create a small api for whatever transport you're using (eg. REST) and then send over the appropriate event data. 
- Setup your server (see http://appsensor.org/getting-started.html) 
- Instrument your apps to call your api for sending events
- Either query the reporting API yourself or wait on our dashboard (my first priority for the next couple of months)

If you're interested in contributing to the dashboard design or development, we'd love to have the help. 

Hope that helps.

Thanks,
John
