### ISSUE TITLE
Q: Production ready?

### ISSUE THREAD

**Issue by judoole** [jtmelton/appsensor#90]
First off, excellent project. I loved the ui when I got the docker-compose example up and running and using appsensor-ws-rest-client-boot-data-generator for generating data. Haven't got around to doing responses yet. 

We are in the process of implementing an Appsensor, and I'm wondering if the projects intention is to be a reference project, or could it be used in a production environment also?

**Comment by jtmelton** [comment]
@judoole thanks for reaching out and the kind words. 

The project is certainly a reference implementation, but it is production ready, and is being used many places. I don't have figures for that, but have regular conversations with folks. We've also had a number of implementations of integrations from folks using the product in the field (but needed an integration we didn't support). Having said that, I would say the UI is the weakest part of the system. The core system/toolkit has been pretty stable for a few years. Downloads via maven have steadily risen ever since the 2.0 release a few years ago (last I looked it was around 5,000 per month).

**Comment by judoole** [comment]
Good to hear @jtmelton!

My first impressions is that it looks very modular and easy to add various responses and database, which is great. Having an engine with logic and well documented detection points is gold for a developer like me, who rarely does security development.

I'll continue on trying to use Appsensor in our project, and hopefully give something back to Appsensor in form of documentation or little bits of code.

**Comment by jtmelton** [comment]
Perfect thanks @judoole, and do let us know if there is anything you need.
